const { UGLY_CITY_MILESTONES } = require("./uglyCityMilestones");

const milestoneConcepts = [
  "Show the Squig or Squigs claiming a dusty empty lot as the first piece of Ugly City. Empty space, crooked signs, fake permits, and overconfident city-building energy all fit here.",
  "Show the first rough community camp: tarps, scrap wood, tents, ropes, supplies, and Squigs trying to make a temporary home look official.",
  "Show Ugly City's first dirt road being built badly. Dust, signs, cones, loops, tiny construction gear, and roadwork confusion all work well.",
  "Show a chaotic storage yard full of crates, barrels, pallets, labels, and badly organized supplies that look important to Ugly City's future.",
  "Show the first workshop where unsafe tools, unfinished inventions, benches, clamps, and Squig productivity immediately get out of hand.",
  "Show a junkyard full of scrap metal, old signs, broken appliances, strange treasures, and Squigs treating trash like city-building material.",
  "Show a crooked water tower, leaky pipes, ladders, puddles, and Squigs dealing with cartoon water pressure or questionable plumbing.",
  "Show funny underground sewer chaos: pipes, tunnels, glowing puddles, cones, slime, maintenance signs, and Squigs exploring somewhere gross but useful.",
  "Show the first trailer park with crooked trailers, lawn chairs, tiny fences, loose wheels, odd decorations, and proudly ugly residential energy.",
  "Show a bridge that feels like a massive achievement even if it crosses something tiny. Crooked supports, loose planks, ribbon cutting, and Squig pride fit well.",
  "Show a junk-built hospital with crooked medical signs, fake doctor gear, duct tape, odd machines, and harmless cartoon medical confusion.",
  "Show a tiny police station with bars, lights, evidence boxes, desks, warning signs, and Squigs enforcing rules they barely understand.",
  "Show a fire hall with tangled hoses, helmets, sirens, a tiny fire truck, fire pole chaos, and Squigs attempting emergency readiness.",
  "Show the first town hall meeting in a crooked civic building with papers, complaint forms, charts, a mayor chair, and very serious nonsense.",
  "Show Ugly City's school with crooked desks, lockers, chalkboards, safety posters, and lessons that make the city less organized than before.",
  "Show a post office overwhelmed by packages, stamps, carts, sorting bins, labels, and Squigs trying to deliver things the wrong way.",
  "Show a power plant powered by bad decisions: levers, gauges, pipes, sparks, warning signs, glowing panels, and lights flickering on.",
  "Show the bank with a tiny vault, fake money, bottle caps, teller windows, tubes, forms, and Squigs pretending finance is under control.",
  "Show a tall crooked apartment block with too many windows, odd balconies, exposed pipes, strange doors, and Squigs trying to live there.",
  "Show a messy warehouse with crates, forklifts, pallets, shrink wrap, mystery orders, impossible aisles, and inventory failure.",
  "Show a crowded market selling weird goods, bad advice, tools, mystery food, bargain signs, vendors, and Squigs trading badly.",
  "Show a gas station with pumps, a small shop, air hoses, suspicious snacks, car wash chaos, and roadside Ugly City energy.",
  "Show a questionable restaurant with crooked tables, steam, mystery food, weird menus, kitchen chaos, and Squigs deciding if it is edible.",
  "Show a shopping mall with empty storefronts, coming-soon signs, escalators, fountains, sale posters, and Squigs excited by retail confusion.",
  "Show an arcade full of glowing cabinets, ticket counters, claw machines, sticky floors, high scores, and Squigs becoming part of the games.",
  "Show a hotel lobby that wants to be fancy but is deeply questionable: front desk, luggage carts, carpets, elevators, tiny soaps, and wrong-room energy.",
  "Show a factory with conveyor belts, warning signs, boxes, machines, assembly lines, and Squigs producing something useless but official.",
  "Show the harbor with crooked docks, cargo containers, nets, boats, ropes, murky water, and Squigs mishandling shipping operations.",
  "Show a casino grand opening with slot machines, chips, cheap carpet, jackpot lights, lounge signs, and Squigs misunderstanding the odds.",
  "Show an office building full of cubicles, meetings, coffee, sticky notes, whiteboards, paperwork, and Squigs getting trapped in corporate nonsense.",
  "Show a ridiculous zoo where the Squigs may be the exhibit. Use cages, signs, empty habitats, observation areas, and attraction chaos.",
  "Show a cloudy aquarium with tanks, bubbles, leaks, strange fish, filter rooms, touch pools, and Squigs being mistaken for marine life.",
  "Show a theme park made from bad engineering: crooked rides, bright signs, mascot tunnels, roller coaster loops, and Squig thrill-ride panic.",
  "Show a sticky movie theater with a big screen, popcorn, recliners, dramatic previews, dim lights, and Squigs causing cinema problems.",
  "Show a bowling alley with crooked lanes, rental shoes, scoreboards, balls, pin machines, and Squigs getting swept into the action.",
  "Show a museum of Ugly City history with artifacts, misspelled plaques, velvet ropes, displays, and Squigs mistaken for exhibits.",
  "Show Ugly City's beach with questionable water, umbrellas, sandcastles, snack stands, floats, and Squigs relaxing somewhere they probably should not.",
  "Show a concert hall with stage lights, curtains, speakers, instruments, balconies, and Squigs making a sound check go wrong.",
  "Show a stadium where nobody agreed on the sport. Mix field markings, goalposts, cones, mascots, referees, fans, and game-day confusion.",
  "Show a nightclub with fog, lights, velvet ropes, dance floor chaos, a DJ booth, and Squigs trying to pass the vibe check.",
  "Show a train station with platforms, delayed boards, confusing signs, suitcases, ticket booths, and Squigs boarding the wrong thing.",
  "Show a subway station with turnstiles, route maps, tunnels, flickering lights, odd train labels, and underground transit confusion.",
  "Show an airport with one runway, luggage carts, counters, mystery gates, departure boards, baggage claim, and Squig travel chaos.",
  "Show a university campus with lecture halls, diplomas, signs, lockers, absurd classes, and Squigs learning or teaching badly.",
  "Show a research lab with beakers, warning labels, testing chambers, red buttons, machines, and questionable Squig science.",
  "Show a TV station with cameras, lights, weather maps, microphones, live graphics, and Squigs accidentally becoming broadcast talent.",
  "Show an observatory with a telescope, star charts, night sky, strange space objects, and Squigs misreading the universe.",
  "Show crooked skyscrapers, cranes, clouds, windows, revolving doors, construction lifts, and Squigs high above an unstable skyline.",
  "Show the luxury district as expensive but ugly: gold-painted details, velvet ropes, fountains, fancy signs, fake elegance, and Squigs acting elite.",
  "Show Old Town with dusty paths, old signs, crooked doors, mailboxes, ancient civic details, and the sense that Ugly City was always like this.",
  "Show the Mayor's Office with a too-important desk, complaint papers, filing cabinets, unsigned approvals, cold coffee, and absent leadership energy.",
  "Show Founders Plaza with benches, bricks, plaques, ribbon, ceremony props, and Squigs celebrating a public space that is already uneven.",
  "Show a heroic but confused city monument under construction, with scaffolding, dust, cranes, tools, and Squigs making it worse.",
  "Show a hidden vault with old city plans, fake treasure, glowing locks, bottle caps, heavy doors, and Squigs scrambling inside.",
  "Show the secret underground side of Ugly City with maintenance tunnels, glowing signs, pipes, hidden doors, trams, and mystery infrastructure.",
  "Show the Grand Gate with banners, flags, turnstiles, entrance signs, decorations, and Squigs opening the city too early.",
  "Show Ugly Castle with crooked towers, flags, a tiny moat, drawbridge problems, cardboard royalty, and Squigs pretending to rule.",
  "Show the Hall of Survivors with portraits, plaques, trophies, curtains, misspelled names, and Squigs becoming part of official history.",
  "Show The Crown as a dramatic ceremonial object with banners, lighting, a chair, applause, and Squigs treating leadership as dangerous.",
  "Show the Founder's Statue being finished with scaffolding, cracked stone, tools, skyline, and Squigs making one last structural mistake.",
  "Show a courthouse with judge bench, jury box, papers, evidence, gavel drama, and Squigs turning law into theater.",
  "Show a permit office with endless forms, closed windows, tickets, chairs, stamps, and Squigs trapped in bureaucracy.",
  "Show a recycling center turning old junk into new junk, with bins, conveyor belts, labels, piles, and sorting mistakes.",
  "Show a bus depot with route signs, benches, tickets, buses, out-of-service confusion, and Squigs stuck in transit loops.",
  "Show a crooked library with tall shelves, overdue notices, whisper signs, weird books, and Squigs lost in the stacks.",
  "Show a laundromat with shaking machines, bubbles, lost socks, dryers, static, and Squigs caught in wash-day chaos.",
  "Show a food court with many counters, trays, sauces, unreadable menus, samples, and Squigs stuck choosing lunch.",
  "Show a city park with crooked trees, benches, ribbon, pond, paths, signs, and Squigs treating weak landscaping like a landmark.",
  "Show a pawn shop packed with lost city items, odd tools, price tags, trophies, lamps, and Squigs treated like collectibles.",
  "Show rooftops with ladders, chimneys, antennas, rooftop bridges, skyline views, and Squigs stranded above the city.",
  "Show a radio tower with antennas, wires, microphones, speakers, static, and Squigs accidentally becoming part of the broadcast.",
  "Show a weather station with radar screens, wind tunnels, fog, storm maps, rain gauges, flags, and Squigs testing forecasts badly.",
  "Show a toll booth on a bad road with exact change signs, cones, coin baskets, traffic, and Squigs arguing over payment.",
  "Show a parking garage with spiral ramps, arrows, tickets, compact spots, echoing honks, and Squigs lost in levels.",
  "Show the Department of Bad Decisions approving terrible plans with stamps, charts, forms, warning signs, and proud administrative failure.",
  "Show the Ugly DMV with endless chairs, photo booths, number signs, forms, closed windows, and Squigs waiting forever.",
  "Show the City Dump as the worst civic landmark: trash hills, rejected appliances, rolling tires, old mattresses, and Squigs blending in.",
  "Show a canal with murky water, gates, tiny boats, bridges, ropes, and Squigs operating water infrastructure badly.",
  "Show a ferry terminal with late boats, dock ropes, tickets, life jackets, damp signs, and Squigs confused by water travel.",
  "Show a crooked boardwalk with games, snack stands, prize booths, loose planks, pier lights, and Squigs getting swept into attractions.",
  "Show a flickering motel with tiny rooms, keychains, peeling signs, ice machine, odd doors, and Squigs checking into questionable comfort.",
  "Show a convention center with booths, banners, folding tables, stage panels, lanyards, and Squigs hosting a disaster-themed event.",
  "Show a suspicious ice cream stand with strange flavors, cones, sprinkles, freezer gear, and Squigs getting tangled in dessert operations.",
  "Show an underground mall with closed kiosks, neon signs, deep escalators, identical shops, and Squigs lost below the city.",
  "Show a clock tower with four wrong times, gears, bells, ropes, ladders, and Squigs trapped in timekeeping problems.",
  "Show a questionable water park with crooked slides, lazy river, tubes, wave pool, signs, and Squigs stuck in water chaos.",
  "Show a community center with folding chairs, posters, sign-up sheets, nametags, lost-and-found bins, and awkward Squig activities.",
  "Show a tattoo shop with flash sheets, mirrors, waiver forms, buzzing tools, warning-sign designs, and Squigs reconsidering choices.",
  "Show a newsstand with flying newspapers, dramatic headlines, crossword chaos, magazines, and Squigs becoming part of the story.",
  "Show a soup kitchen with a huge pot, bowls, ladles, folding tables, recipe signs, and Squigs serving community chaos.",
  "Show a security office with camera monitors, files, walkie-talkies, flickering screens, and Squigs missing the obvious problem.",
  "Show a monorail station above Ugly City with sleek trains, unstable supports, tourist signs, platforms, and looping transit confusion.",
  "Show a botanical garden with greenhouse glass, warning plants, vines, glowing flowers, pollen, and Squigs being handled by nature.",
  "Show a statue factory with molds, cranes, chisels, half-finished monuments, polishing machines, and Squigs accidentally cast in history.",
  "Show an emergency bunker with heavy hatch, canned food, whistles, warning posters, maps, drills, and Squigs overprepared for nonsense.",
  "Show the Records Office with filing cabinets, archives, folders, complaint records, labels, and Squigs misfiled into city history.",
  "Show The Last Alley as a narrow final corner of Ugly City with brick walls, signs, dumpsters, dead ends, and suspicious civic atmosphere.",
  "Show the Final Permit Desk as paperwork turned into a final boss: stamps, forms, tiny window, missing initials, and Squig frustration.",
  "Show the City Hall Steps with banners, carpet, crowds, dust, final doors, and Squigs climbing toward official city status.",
  "Show the Founder's Office overlooking Ugly City, with crooked desk, city plans, cracked nameplate, important chair, and a Squig ready to claim the title.",
];

const UGLY_CITY_MILESTONE_CONCEPTS = Object.freeze(
  UGLY_CITY_MILESTONES.reduce((concepts, milestone, index) => {
    concepts[milestone.key] = milestoneConcepts[index];
    return concepts;
  }, {})
);

function getUglyCityMilestoneConceptByKey(key) {
  return UGLY_CITY_MILESTONE_CONCEPTS[key] || null;
}

module.exports = {
  UGLY_CITY_MILESTONE_CONCEPTS,
  getUglyCityMilestoneConceptByKey,
};
